using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;

/// <summary>
/// Tools > Build Prison Level  (v3)
///
/// Changes from v2:
///   • WallH raised to 4 units throughout
///   • Hallway: solid end walls added (fully enclosed)
///   • Hallway south wall: 2 doorway openings leading into maze (col 2 and col 5)
///   • Maze: full 8x10 grid, 6-unit corridors, 12 rooms, key + exit + 8 enemy spawns
///   • Materials loaded from Assets/Materials/Prison/ if available
/// </summary>
public static class BuildPrisonLevel
{
    // ── Dimensions ────────────────────────────────────────────────────────────
    const float WallH  = 4.0f;
    const float WallT  = 0.5f;
    const float CellW  = 3.5f;
    const float CellD  = 4.0f;
    const int   NCells = 8;
    const float HallW  = 4.0f;   // hallway depth (Z)

    // Derived hallway extents
    static float CellsW => NCells * CellW;   // 28
    static float HallX0 => -(CellsW * 0.5f) - 4f;   // -18
    static float HallX1 =>  (CellsW * 0.5f) + 4f;   // +18
    static float OX     => -(CellsW * 0.5f);          // -14 (cell block left edge)

    // ── Maze grid ─────────────────────────────────────────────────────────────
    const int   MCOLS   = 8;
    const int   MROWS   = 10;
    const float MCELL   = 4.0f;   // walkable corridor width (~2 players side by side)
    const float MGAP    = 2.5f;   // wall thickness between cells (footprint stays 52x65)
    const float MSTRIDE = MCELL + MGAP;  // 6.5 — unchanged, so outer dimensions stay same

    const float MX0 = -26f;      // maze west boundary
    const float MZ1 = -4f;       // maze north boundary (= hallway south wall)

    // Maze passage arrays — generated by gen_maze.py (seed=42, 80/80 reachable)
    static readonly bool[,] vOpen = {   // [c=0..6][r=0..9]  east passage from col c
        { true,  true,  true,  false, true,  true,  true,  true,  true,  true  },
        { false, true,  true,  true,  false, true,  false, true,  false, true  },
        { true,  true,  true,  true,  true,  false, false, true,  true,  true  },
        { true,  false, false, false, true,  false, true,  true,  true,  true  },
        { true,  true,  true,  true,  true,  true,  true,  true,  false, true  },
        { true,  false, true,  false, false, false, true,  false, true,  false },
        { true,  true,  true,  true,  true,  false, true,  true,  false, true  },
    };
    static readonly bool[,] hOpen = {  // [c=0..7][r=0..8]  south passage from row r
        { true,  true,  false, true,  true,  false, true,  true,  true  },
        { false, false, false, true,  false, false, false, true,  false },
        { true,  true,  false, false, false, true,  true,  false, true  },
        { true,  false, true,  false, true,  false, true,  false, true  },
        { true,  true,  true,  false, true,  false, false, false, true  },
        { false, true,  false, true,  false, true,  true,  true,  true  },
        { false, true,  false, true,  true,  true,  true,  false, true  },
        { true,  false, true,  true,  true,  true,  true,  true,  true  },
    };

    // Hallway entry columns (top of these columns connect to hallway south wall)
    static readonly int[] EntryColumns = { 2, 5 };

    // Rooms: 12 cells designated as rooms (slightly enlarged + named)
    static readonly HashSet<(int, int)> RoomCells = new HashSet<(int, int)> {
        (0,2),(3,2),(5,1),(2,5),(0,5),(6,4),(3,4),(4,6),(7,4),(6,8),(2,7),(1,7),
    };

    // Key at (6,8): far right, row 8 of 10 — far from cell block
    static readonly (int c, int r) KeyCell  = (6, 8);
    // Exit at (3,4): centre of maze
    static readonly (int c, int r) ExitCell = (3, 4);

    static readonly (int c, int r)[] EnemySpawnCells = {
        (7,7),(1,0),(7,5),(7,8),(3,7),(3,8),(0,6),(6,3),
    };

    // ── Cached materials ──────────────────────────────────────────────────────
    static Material _wallMat, _floorMat, _barMat, _exitMat, _keyMat;

    // ── Entry point ───────────────────────────────────────────────────────────
    [MenuItem("Tools/Build Prison Level")]
    public static void Run()
    {
        if (!EditorUtility.DisplayDialog("Build Prison Level",
            "DELETE all existing level geometry and rebuild?",
            "Yes — Rebuild", "Cancel")) return;

        LoadMaterials();
        ClearExistingGeometry();

        var goCell   = Reg(new GameObject("CellBlock"));
        var goHall   = Reg(new GameObject("Hallway"));
        var goMWalls = Reg(new GameObject("Maze_Walls"));
        var goMRooms = Reg(new GameObject("Maze_Rooms"));
        var goSpawns = Reg(new GameObject("Spawn_Points"));
        var goEnemy  = Reg(new GameObject("Enemy_Spawns"));
        var goKey    = Reg(new GameObject("Key"));
        var goExit   = Reg(new GameObject("Exit"));

        BuildCellBlock(goCell.transform, goSpawns.transform);
        BuildHallway  (goHall.transform);
        BuildMaze     (goMWalls.transform, goMRooms.transform,
                       goEnemy.transform, goKey.transform, goExit.transform);

        // Ground under everything
        MakeCube("Ground", null,
            new Vector3(0f, -WallT * 0.5f, -36f),
            new Vector3(200f, WallT, 200f), _floorMat);

        EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
        EditorUtility.DisplayDialog("Build Prison Level — Done",
            "Maze dimensions: ~52 x 65 units (X: -26..+26, Z: -69..-4)\n\n" +
            "12 rooms accessible from corridors:\n" +
            "(0,2)(3,2)(5,1)(2,5)(0,5)(6,4)(3,4)(4,6)(7,4)(6,8)(2,7)(1,7)\n\n" +
            "Key: cell (6,8) — far right, row 8 of 10 (deep in maze)\n" +
            "Exit door: cell (3,4) — centre of maze\n" +
            "Enemy spawns: 8 placed throughout corridors and rooms\n\n" +
            "All 80 grid cells confirmed reachable from both hallway entries.\n\n" +
            "Save (Ctrl+S) and Play.", "OK");
    }

    // ── Material loading ──────────────────────────────────────────────────────
    static void LoadMaterials()
    {
        _wallMat  = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/Prison/Wall_Material.mat")
                 ?? FallbackMat(new Color(0.22f, 0.22f, 0.22f));
        _floorMat = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/Prison/Floor_Material.mat")
                 ?? FallbackMat(new Color(0.28f, 0.22f, 0.15f));
        _barMat   = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/Prison/Cell_Bar_Material.mat")
                 ?? FallbackMat(new Color(0.18f, 0.18f, 0.20f));
        _exitMat  = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/Prison/Exit_Material.mat")
                 ?? FallbackMat(new Color(0.8f, 0.08f, 0.08f));
        _keyMat   = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/Prison/Key_Material.mat")
                 ?? FallbackMat(new Color(1f, 0.85f, 0f));
    }

    static Material FallbackMat(Color c)
    {
        Shader sh = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
        var m = new Material(sh);
        if (m.HasProperty("_BaseColor")) m.SetColor("_BaseColor", c); else m.color = c;
        return m;
    }

    // ── Clear existing geometry ───────────────────────────────────────────────
    static void ClearExistingGeometry()
    {
        string[] names = {
            "CellBlock","Hallway","Maze_Walls","Maze_Rooms","Spawn_Points",
            "Enemy_Spawns","Key","Exit","Ground","Maze","MazeWalls","MazeRooms",
            "Walls","Rooms","Spawns","Floor",
        };
        foreach (var n in names)
        {
            var go = GameObject.Find(n);
            if (go != null) Undo.DestroyObjectImmediate(go);
        }
        foreach (var go in UnityEngine.SceneManagement.SceneManager
                               .GetActiveScene().GetRootGameObjects())
        {
            if (go.name.StartsWith("SpawnPoint") || go.name.StartsWith("EnemySpawn"))
                Undo.DestroyObjectImmediate(go);
        }
    }

    // ── Cell block ────────────────────────────────────────────────────────────
    static void BuildCellBlock(Transform par, Transform spawnPar)
    {
        float hy = WallH * 0.5f;

        // Shared back wall
        MakeWall("BackWall", par,
            cx: OX + CellsW * 0.5f, cy: hy, cz: CellD + WallT * 0.5f,
            sx: CellsW + WallT * 2f, sy: WallH, sz: WallT, mat: _wallMat);

        for (int i = 0; i < NCells; i++)
        {
            float x0 = OX + i * CellW;
            float x1 = x0 + CellW;
            float cx = (x0 + x1) * 0.5f;
            string nm = $"Cell_{i + 1}";

            if (i == 0)
                MakeWall($"{nm}_WallL", par, cx: x0 - WallT * 0.5f, cy: hy,
                    cz: CellD * 0.5f, sx: WallT, sy: WallH, sz: CellD, mat: _wallMat);
            MakeWall($"{nm}_WallR", par, cx: x1 + WallT * 0.5f, cy: hy,
                cz: CellD * 0.5f, sx: WallT, sy: WallH, sz: CellD, mat: _wallMat);

            MakeSlab($"{nm}_Floor",   par, cx, -WallT * 0.5f,          CellD * 0.5f, CellW, CellD, _floorMat);

            // Bar front — full-height opening (no strip above door)
            const float DoorW = 1.4f;
            float pillarW = (CellW - DoorW) * 0.5f;
            MakeWall($"{nm}_BarL", par, cx: x0 + pillarW * 0.5f, cy: hy,
                cz: -WallT * 0.5f, sx: pillarW, sy: WallH, sz: WallT, mat: _barMat);
            MakeWall($"{nm}_BarR", par, cx: x1 - pillarW * 0.5f, cy: hy,
                cz: -WallT * 0.5f, sx: pillarW, sy: WallH, sz: WallT, mat: _barMat);

            var sp = Reg(new GameObject($"SpawnPoint_{i + 1}"));
            sp.tag = "SpawnPoint";
            sp.transform.SetParent(spawnPar);
            sp.transform.position = new Vector3(cx, 1.0f, CellD * 0.6f);
        }
    }

    // ── Hallway ───────────────────────────────────────────────────────────────
    static void BuildHallway(Transform par)
    {
        float hallLen = HallX1 - HallX0;   // 36
        float hallCX  = (HallX0 + HallX1) * 0.5f;
        float hallCZ  = -HallW * 0.5f;
        float hy      = WallH * 0.5f;

        MakeSlab("Hall_Floor", par, hallCX, -WallT * 0.5f, hallCZ, hallLen, HallW, _floorMat);

        // ── LEFT END WALL (fully solid) ───────────────────────────────────────
        MakeWall("Hall_LeftEnd", par,
            cx: HallX0 - WallT * 0.5f, cy: hy, cz: hallCZ,
            sx: WallT, sy: WallH, sz: HallW, mat: _wallMat);

        // ── RIGHT END WALL (fully solid) ──────────────────────────────────────
        MakeWall("Hall_RightEnd", par,
            cx: HallX1 + WallT * 0.5f, cy: hy, cz: hallCZ,
            sx: WallT, sy: WallH, sz: HallW, mat: _wallMat);

        // ── SOUTH WALL — three pieces with two maze-entry doorways ─────────────
        // Entry openings align with maze grid cols 2 and 5:
        float col2x0 = MX0 + 2 * MSTRIDE;           // -26 + 13  = -13
        float col2x1 = col2x0 + MCELL;              //            = -7
        float col5x0 = MX0 + 5 * MSTRIDE;           // -26 + 32.5 = 6.5
        float col5x1 = col5x0 + MCELL;              //             = 12.5

        float southZ = MZ1 - WallT * 0.5f;          // = -4.25
        float swy    = WallH * 0.5f;

        // Left piece: HallX0(-18) to col2x0(-13)
        MakeWall("Hall_SouthL", par,
            cx: (HallX0 + col2x0) * 0.5f, cy: swy, cz: southZ,
            sx: col2x0 - HallX0, sy: WallH, sz: WallT, mat: _wallMat);

        // Middle piece: col2x1(-7) to col5x0(6.5)
        MakeWall("Hall_SouthM", par,
            cx: (col2x1 + col5x0) * 0.5f, cy: swy, cz: southZ,
            sx: col5x0 - col2x1, sy: WallH, sz: WallT, mat: _wallMat);

        // Right piece: col5x1(12.5) to HallX1(18)
        MakeWall("Hall_SouthR", par,
            cx: (col5x1 + HallX1) * 0.5f, cy: swy, cz: southZ,
            sx: HallX1 - col5x1, sy: WallH, sz: WallT, mat: _wallMat);
    }

    // ── Maze ──────────────────────────────────────────────────────────────────
    static void BuildMaze(Transform wPar, Transform rPar,
                          Transform ePar, Transform kPar, Transform exPar)
    {
        float floorY = 0f;
        float hy     = WallH * 0.5f;

        // Total maze extents
        float mazeX1  = MX0 + MCOLS * MSTRIDE;  // 26
        float mazeZ0  = MZ1 - MROWS * MSTRIDE;  // -69

        // ── One big floor for the entire maze area ────────────────────────────
        MakeSlab("Maze_Floor", rPar,
            cx: (MX0 + mazeX1) * 0.5f,
            cy: floorY - WallT * 0.5f,
            cz: (MZ1 + mazeZ0) * 0.5f,
            sx: mazeX1 - MX0,
            sz: MZ1 - mazeZ0,
            mat: _floorMat);

        // ── Outer boundary walls ──────────────────────────────────────────────
        float mazeDepth = MZ1 - mazeZ0;    // positive: from -69 to -4 = 65
        float mazeCZ    = (MZ1 + mazeZ0) * 0.5f;   // -36.5
        float mazeWidth = mazeX1 - MX0;   // 52

        // West wall
        MakeWall("Maze_WestWall", wPar,
            cx: MX0 - WallT * 0.5f, cy: hy, cz: mazeCZ,
            sx: WallT, sy: WallH, sz: mazeDepth, mat: _wallMat);
        // East wall
        MakeWall("Maze_EastWall", wPar,
            cx: mazeX1 + WallT * 0.5f, cy: hy, cz: mazeCZ,
            sx: WallT, sy: WallH, sz: mazeDepth, mat: _wallMat);
        // South wall
        MakeWall("Maze_SouthWall", wPar,
            cx: (MX0 + mazeX1) * 0.5f, cy: hy, cz: mazeZ0 - WallT * 0.5f,
            sx: mazeWidth + WallT, sy: WallH, sz: WallT, mat: _wallMat);

        // North boundary — 3 pieces (matching hallway south wall gaps)
        float col2x0 = MX0 + 2 * MSTRIDE;
        float col2x1 = col2x0 + MCELL;
        float col5x0 = MX0 + 5 * MSTRIDE;
        float col5x1 = col5x0 + MCELL;
        float northZ = MZ1 - WallT * 0.5f;

        // West of left entry
        MakeWall("Maze_NorthWL", wPar,
            cx: (MX0 + col2x0) * 0.5f, cy: hy, cz: northZ,
            sx: col2x0 - MX0, sy: WallH, sz: WallT, mat: _wallMat);
        // Between entries
        MakeWall("Maze_NorthWM", wPar,
            cx: (col2x1 + col5x0) * 0.5f, cy: hy, cz: northZ,
            sx: col5x0 - col2x1, sy: WallH, sz: WallT, mat: _wallMat);
        // East of right entry
        MakeWall("Maze_NorthWR", wPar,
            cx: (col5x1 + mazeX1) * 0.5f, cy: hy, cz: northZ,
            sx: mazeX1 - col5x1, sy: WallH, sz: WallT, mat: _wallMat);

        // ── Interior corridor walls from grid ─────────────────────────────────
        // Walls adjacent to room cells are suppressed — rooms build their own.
        for (int c = 0; c < MCOLS; c++)
        {
            for (int r = 0; r < MROWS; r++)
            {
                bool thisRoom  = RoomCells.Contains((c, r));
                float cx = CellCX(c);
                float cz = CellCZ(r);
                float x0 = MX0 + c * MSTRIDE;
                float z1 = MZ1 - r * MSTRIDE;

                // Vertical wall on EAST side (between c and c+1)
                if (c < MCOLS - 1 && !vOpen[c, r])
                {
                    bool nextRoom = RoomCells.Contains((c + 1, r));
                    if (!thisRoom && !nextRoom)
                        MakeWall($"VW_{c}_{r}", wPar,
                            cx: x0 + MCELL + MGAP * 0.5f,
                            cy: hy, cz: cz,
                            sx: MGAP, sy: WallH, sz: MCELL, mat: _wallMat);
                }

                // Horizontal wall on SOUTH side (between r and r+1)
                if (r < MROWS - 1 && !hOpen[c, r])
                {
                    bool nextRoom = RoomCells.Contains((c, r + 1));
                    if (!thisRoom && !nextRoom)
                        MakeWall($"HW_{c}_{r}", wPar,
                            cx: cx, cy: hy,
                            cz: z1 - MCELL - MGAP * 0.5f,
                            sx: MCELL, sy: WallH, sz: MGAP, mat: _wallMat);
                }
            }
        }

        // ── Proper enclosed rooms ─────────────────────────────────────────────
        // Each room uses the full MSTRIDE × MSTRIDE footprint (4-unit walkable
        // corridor + 2.5-unit wall on each side = 6.5-unit stride total).
        // Four solid walls are built; the corridor-facing wall gets a narrow
        // 2.5-unit doorway opening instead of a full passage.
        const float ROOM_DOOR = 2.5f;   // doorway opening width in room wall

        foreach (var (rc, rr) in RoomCells)
        {
            // Room world bounds (full stride square)
            float rx0 = MX0 + rc * MSTRIDE;
            float rx1 = rx0 + MSTRIDE;
            float rz1 = MZ1 - rr * MSTRIDE;
            float rz0 = rz1 - MSTRIDE;
            float rcx  = (rx0 + rx1) * 0.5f;
            float rcz  = (rz0 + rz1) * 0.5f;
            string nm  = $"Room_{rc}_{rr}";

            // Determine entry direction — first open passage (N, S, E, W)
            bool openN = (rr > 0) && hOpen[rc, rr - 1];
            bool openS = (rr < MROWS - 1) && hOpen[rc, rr];
            bool openE = (rc < MCOLS - 1) && vOpen[rc, rr];
            bool openW = (rc > 0) && vOpen[rc - 1, rr];
            // Top-of-maze entries also count as north openings for row 0
            bool isEntry = (rr == 0) && (rc == EntryColumns[0] || rc == EntryColumns[1]);
            if (isEntry) openN = true;

            // Choose one direction for the doorway (priority: N, S, E, W)
            string doorDir = openN ? "N" : openS ? "S" : openE ? "E" : "W";

            // ── Four room walls ───────────────────────────────────────────────
            // North wall (or with doorway)
            BuildRoomWall(nm + "_WallN", wPar,
                wallCX: rcx, wallCZ: rz1 + WallT * 0.5f,
                wallSX: MSTRIDE, wallSZ: WallT,
                hasDoor: doorDir == "N", doorW: ROOM_DOOR,
                horizontal: true);

            // South wall (or with doorway)
            BuildRoomWall(nm + "_WallS", wPar,
                wallCX: rcx, wallCZ: rz0 - WallT * 0.5f,
                wallSX: MSTRIDE, wallSZ: WallT,
                hasDoor: doorDir == "S", doorW: ROOM_DOOR,
                horizontal: true);

            // East wall (or with doorway)
            BuildRoomWall(nm + "_WallE", wPar,
                wallCX: rx1 + WallT * 0.5f, wallCZ: rcz,
                wallSX: WallT, wallSZ: MSTRIDE,
                hasDoor: doorDir == "E", doorW: ROOM_DOOR,
                horizontal: false);

            // West wall (or with doorway)
            BuildRoomWall(nm + "_WallW", wPar,
                wallCX: rx0 - WallT * 0.5f, wallCZ: rcz,
                wallSX: WallT, wallSZ: MSTRIDE,
                hasDoor: doorDir == "W", doorW: ROOM_DOOR,
                horizontal: false);
        }

        // ── Key prop ──────────────────────────────────────────────────────────
        MakeCube("KeyPickup", kPar,
            new Vector3(CellCX(KeyCell.c), floorY + 0.5f, CellCZ(KeyCell.r)),
            new Vector3(0.5f, 0.5f, 0.5f), _keyMat);

        // ── Exit door ─────────────────────────────────────────────────────────
        MakeCube("ExitDoor", exPar,
            new Vector3(CellCX(ExitCell.c), hy, CellCZ(ExitCell.r)),
            new Vector3(2.5f, WallH, WallT * 2f), _exitMat);

        // ── Enemy spawn points ────────────────────────────────────────────────
        foreach (var (ec, er) in EnemySpawnCells)
        {
            var sp = Reg(new GameObject($"EnemySpawn_{ec}_{er}"));
            sp.transform.SetParent(ePar);
            sp.transform.position = new Vector3(CellCX(ec), 1.0f, CellCZ(er));
        }
    }

    // ── Cell coordinate helpers ───────────────────────────────────────────────
    static float CellCX(int c) => MX0 + c * MSTRIDE + MCELL * 0.5f;
    static float CellCZ(int r) => MZ1 - r * MSTRIDE - MCELL * 0.5f;

    // ── Room wall builder ─────────────────────────────────────────────────────
    // Builds one wall of a room, optionally with a narrow doorway opening.
    // horizontal=true  → wall runs along X (north/south wall of room)
    // horizontal=false → wall runs along Z (east/west wall of room)
    static void BuildRoomWall(string nm, Transform par,
                               float wallCX, float wallCZ,
                               float wallSX, float wallSZ,
                               bool hasDoor, float doorW,
                               bool horizontal)
    {
        if (!hasDoor)
        {
            MakeWall(nm, par, wallCX, WallH * 0.5f, wallCZ,
                     wallSX, WallH, wallSZ, _wallMat);
            return;
        }

        // Split wall into two pieces flanking the doorway
        // "span" = the wall's extent along its long axis
        float span    = horizontal ? wallSX : wallSZ;
        float pieceW  = (span - doorW) * 0.5f;
        float offset  = (pieceW + doorW) * 0.5f;   // centre of each piece from wall centre

        if (horizontal)
        {
            // Left piece
            MakeWall(nm + "_L", par, wallCX - offset, WallH * 0.5f, wallCZ,
                     pieceW, WallH, wallSZ, _wallMat);
            // Right piece
            MakeWall(nm + "_R", par, wallCX + offset, WallH * 0.5f, wallCZ,
                     pieceW, WallH, wallSZ, _wallMat);
        }
        else
        {
            // Near piece
            MakeWall(nm + "_A", par, wallCX, WallH * 0.5f, wallCZ - offset,
                     wallSX, WallH, pieceW, _wallMat);
            // Far piece
            MakeWall(nm + "_B", par, wallCX, WallH * 0.5f, wallCZ + offset,
                     wallSX, WallH, pieceW, _wallMat);
        }
    }

    // ── Geometry helpers ──────────────────────────────────────────────────────
    static void MakeWall(string nm, Transform par,
                         float cx, float cy, float cz,
                         float sx, float sy, float sz,
                         Material mat = null)
        => MakeCube(nm, par, new Vector3(cx, cy, cz), new Vector3(sx, sy, sz), mat);

    static void MakeSlab(string nm, Transform par,
                         float cx, float cy, float cz,
                         float sx, float sz,
                         Material mat = null)
        => MakeCube(nm, par, new Vector3(cx, cy, cz), new Vector3(sx, WallT, sz), mat);

    static void MakeCube(string nm, Transform par,
                         Vector3 pos, Vector3 scale,
                         Material mat = null)
    {
        var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
        go.name             = nm;
        go.transform.position   = pos;
        go.transform.localScale = scale;
        go.isStatic         = true;
        if (par != null) go.transform.SetParent(par, true);

        if (mat != null)
        {
            var mr = go.GetComponent<MeshRenderer>();
            if (mr != null) mr.sharedMaterial = mat;
        }
        Undo.RegisterCreatedObjectUndo(go, "Build Prison Level");
    }

    static GameObject Reg(GameObject go)
    {
        Undo.RegisterCreatedObjectUndo(go, "Build Prison Level");
        return go;
    }
}
